USE [DizimoDB]
GO

/****** Object:  Table [dbo].[FluxoTipo]    Script Date: 09/07/2022 10:32:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FluxoTipo](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](50) NOT NULL,
 CONSTRAINT [PK_FluxoTipo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


INSERT INTO [FluxoTipo] (Descricao) VALUES('Dízimo')
INSERT INTO [FluxoTipo] (Descricao) VALUES('Oferta')
INSERT INTO [FluxoTipo] (Descricao) VALUES('Voto')
